### ISSUE TITLE
Small words as part of a noun or proper noun are lower-cased

### ISSUE THREAD

**Issue by TxHawks** [gouch/to-title-case#14]
The script obviously has no way of "knowing" the grammatical role of a word, which sometimes produces erroneous output.

For instance: `"Review: The book On Again Off Again is horrible".toTitleCase()` will produce `Review: The Book on Again Off Again Is Horrible`, which is wrong, as `On Again Off Again` is a proper noun in this case.

Similarly, the output of `"The on button, a history".toTitleCase()` will be `The on Button, a History`, which again, is erroneous as `on button` is a noun here, and should therefore be capitalized.

I can think of no programmatic way of solving such edge case, but think that it should at least be possible to manually override lower-casing, maybe by providing an argument controlling the forced lower-casing:
`"Review: The book On Again Off Again is horrible".toTitleCase()` ==> `Review: The Book on Again Off Again Is Horrible`

`"Review: The book On Again Off Again is horrible".toTitleCase(false)` ==> `Review: The Book On Again Off Again Is Horrible`

**Comment by tomByrer** [comment]
I believe that book titles should be quoted.

**Comment by gouch** [comment]
What @tomByrer said about quotes is true: In your examples adding quote marks around the titles would prevent their first word from being lowercased.

I want to avoid adding configuration options, but I'll keep it in mind if more issues like this come up.
