### ISSUE TITLE
Forcing specific case in a title

### ISSUE THREAD

**Issue by h519** [gouch/to-title-case#18]
I really like this function! It is tremendously helpful in insuring that all user-entered titles have a uniform format.  However, there are sometimes exceptions, particularly in technical terms

For example, for the title "Degradation of mRNAs for Centromere and Telomere-Related Genes in Saccharomyces Cerevisiae"
the standard latin format for naming would have cerevisiae in lower case.  

Would it be possible for you to incorporate a "tag" for your javascript function where it would pass the case through unchanged.  In other words, if the tag was %%, the entry 
"Genes In %%Saccharomyces cerevisiae%%"".toTitleCase()
would return the string "Genes in Saccharomyces cerevisiae" instead of Genes in Saccharomyces Cerevisiae?

This may be helpful for other users who want specific capitalization formats for specific words.

Thanks again!
Tom

**Comment by gouch** [comment]
(I'm sorta aware of the latin _Genus species_ capitalization pattern, but I was under the impression that it applied to normal/sentence context, like how you capitalize a proper noun in a sentence. Title case style supersedes that imo.)

So how to treat special cases (heh) where you have a good reason for a word to be lowercased. I don't know yet. An escape character (e.g. `Saccharomyces \cerevisiae`) that means *leave this alone* is certainly a strategy, but 1) I'm not sure how familiar that convention is for the average non-programmer, non–Markdown writer, and 2) I'm not sure if reaching the point where a site needs that feature means we've already exhausted the use of a simplistic JS function.

Do you think the the backslash escape character would be familiar enough for your users?

**Comment by h519** [comment]
My project is a database of bibliographic references by faculty.  In addition to the Genus species (which, from what I gather is lower case even in titles), there are poems that may have irregular case.  I would  avoid using backslash as an escape character because it might lead to confusion its usage in programming.  I made a quick-and-dirty wrapper around your function that will keep the case of anything enclosed in %% with the same case as the original text.  Not nearly as elegant as your function, but it seems to accomplish what I needed to do. I just tell my users to use this tag if they are in doubt.

Thanks,
Tom

function TitleCase(Title) {
      var OrigTitle = Title;
      Title = Title.toTitleCase(); // Convert case of title
      var CorrectTitle = ""
      var SearchStart = 0;
      var CaseTag = "%%";
      
      while (1) {
      
          var SearchString = OrigTitle.slice(SearchStart);
          var tag1 = SearchString.indexOf(CaseTag);
          var tag2 = -1;
          if (tag1 >=0) {
             var SubTitle = SearchString.slice(tag1+2)
             tag2 = SubTitle.indexOf(CaseTag);
             if (tag2 >= 0) {
                var CorrectTitle = SearchString.slice(tag1+2,tag1+2+tag2)
             }
             if (CorrectTitle != "") {
                var reg = new RegExp('('+CorrectTitle+')', 'gi');
                Title = Title.replace(reg, CorrectTitle);
             }
             SearchStart = SearchStart+tag1+2+tag2+2;
          }
          else {
             break;
          }
      }
      Title = Title.replace(/%%/g,"");   // Strip off %% tag 
      return Title;
}

**Comment by gouch** [comment]
Thanks for explaining the use case and I'm glad you got a solution working for you. I'll keep the overall issue in mind for future releases
